environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: WMF 4
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

install:
  - ps: nuget install Pester -Version 5.1.0 -source https://www.powershellgallery.com/api/v2 -outputDirectory "$env:ProgramFiles\WindowsPowerShell\Modules\." -ExcludeVersion

build_script:
  - ps: 'Building...'

test_script:
  - ps: Invoke-Pester
